// <auto-generated />
namespace DWD273_Final_Project_Revised.ApplicationDBMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuickChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuickChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201705162150400_QuickChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
